import 'package:flutter/material.dart';

class Product {
  final String image, title, description, categories;
  final int price, size, id;
  final Color color;
  Product(
      {this.id,
      this.image,
      this.title,
      this.price,
      this.description,
      this.size,
      this.color,
      this.categories});
}

List<Product> products = [
  Product(
    id: 1,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_1.png",
    color: Color(0xFF3D82AE),
    categories: "Hand bags",
  ),
  Product(
    id: 2,
    title: "Belt Bag",
    price: 234,
    size: 8,
    description: dummyText,
    image: "assets/images/bag_2.png",
    color: Color(0xFFD3A984),
    categories: "Hand bags",
  ),
  Product(
    id: 3,
    title: "Hang Top",
    price: 234,
    size: 10,
    description: dummyText,
    image: "assets/images/bag_3.png",
    color: Color(0xFF989493),
    categories: "Hand bags",
  ),
  Product(
    id: 4,
    title: "Old Fashion",
    price: 234,
    size: 11,
    description: dummyText,
    image: "assets/images/bag_4.png",
    color: Color(0xFFE6B398),
    categories: "Hand bags",
  ),
  Product(
    id: 5,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_5.png",
    color: Color(0xFFFB7883),
    categories: "Hand bags",
  ),
  Product(
    id: 6,
    title: "Office Code",
    price: 234,
    size: 12,
    description: dummyText,
    image: "assets/images/bag_6.png",
    color: Color(0xFFAEAEAE),
    categories: "Hand bags",
  ),
  Product(
    id: 7,
    title: "Pink & Brown",
    price: 120,
    size: 10,
    description: dummyText,
    image: "assets/images/shoes_1.png",
    color: Color(0xFFFF4081),
    categories: "Footwear",
  ),
  Product(
    id: 8,
    title: "Blue & Brown",
    price: 120,
    size: 10,
    description: dummyText,
    image: "assets/images/shoes_2.png",
    color: Color(0xFF00756F),
    categories: "Footwear",
  ),
  Product(
    id: 9,
    title: "All Black",
    price: 120,
    size: 10,
    description: dummyText,
    image: "assets/images/shoes_3.png",
    color: Color(0xFF989493),
    categories: "Footwear",
  ),
  Product(
    id: 10,
    title: "Pink & Black",
    price: 120,
    size: 10,
    description: dummyText,
    image: "assets/images/shoes_4.png",
    color: Color(0xFFC51162),
    categories: "Footwear",
  ),
  Product(
    id: 11,
    title: "White & Brown",
    price: 120,
    size: 10,
    description: dummyText,
    image: "assets/images/shoes_5.png",
    color: Color(0xFFFFCA29),
    categories: "Footwear",
  ),
  Product(
    id: 12,
    title: "Blue & Brown",
    price: 120,
    size: 10,
    description: dummyText,
    image: "assets/images/shoes_6.png",
    color: Color(0xFF00B0FF),
    categories: "Footwear",
  ),
  Product(
    id: 13,
    title: "Golden Chain",
    price: 140,
    size: 15,
    description: dummyText,
    image: "assets/images/jewel_1.png",
    color: Color(0xFFFFE082),
    categories: "Jewellery",
  ),
  Product(
    id: 14,
    title: "Red Necklace",
    price: 125,
    size: 12,
    description: dummyText,
    image: "assets/images/jewel_2.png",
    color: Color(0xFFFF8A80),
    categories: "Jewellery",
  ),
  Product(
    id: 15,
    title: "Golden Hearts",
    price: 115,
    size: 10,
    description: dummyText,
    image: "assets/images/jewel_3.png",
    color: Color(0xFFFFE082),
    categories: "Jewellery",
  ),
  Product(
    id: 16,
    title: "Golden Ring",
    price: 100,
    size: 6,
    description: dummyText,
    image: "assets/images/jewel_4.png",
    color: Color(0xFFB0BEC5),
    categories: "Jewellery",
  ),
  Product(
    id: 17,
    title: "Sliver Ring",
    price: 90,
    size: 6,
    description: dummyText,
    image: "assets/images/jewel_5.png",
    color: Color(0xFF00B0FF),
    categories: "Jewellery",
  ),
  Product(
    id: 18,
    title: "Tiara Crown",
    price: 175,
    size: 12,
    description: dummyText,
    image: "assets/images/jewel_6.png",
    color: Color(0xFFF48FB1),
    categories: "Jewellery",
  ),
  Product(
    id: 19,
    title: "Dress Collection",
    price: 550,
    size: 12,
    description: dummyText,
    image: "assets/images/dress_1.png",
    color: Color(0xFF9CCC65),
    categories: "Dressies",
  ),
  Product(
    id: 20,
    title: "Red Dress",
    price: 125,
    size: 12,
    description: dummyText,
    image: "assets/images/dress_2.png",
    color: Color(0xFFFF1744),
    categories: "Dressies",
  ),
  Product(
    id: 21,
    title: "Pink Frock",
    price: 175,
    size: 12,
    description: dummyText,
    image: "assets/images/dress_3.png",
    color: Color(0xFFFF4081),
    categories: "Dressies",
  ),
  Product(
    id: 22,
    title: "Flower Frock",
    price: 75,
    size: 12,
    description: dummyText,
    image: "assets/images/dress_4.png",
    color: Color(0xFFFF6E40),
    categories: "Dressies",
  ),
  Product(
    id: 23,
    title: "Short Red Frock",
    price: 155,
    size: 12,
    description: dummyText,
    image: "assets/images/dress_5.png",
    color: Color(0xFFEF5350),
    categories: "Dressies",
  ),
  Product(
    id: 24,
    title: "Flower Frock",
    price: 95,
    size: 12,
    description: dummyText,
    image: "assets/images/dress_6.png",
    color: Color(0xFFFFCC80),
    categories: "Dressies",
  ),
  Product(
    id: 25,
    title: "Makeup Kit",
    price: 135,
    size: 12,
    description: dummyText,
    image: "assets/images/makeup_1.png",
    color: Color(0xFFF48FB1),
    categories: "Makeup",
  ),
  Product(
    id: 26,
    title: "Shade Box",
    price: 75,
    size: 12,
    description: dummyText,
    image: "assets/images/makeup_2.png",
    color: Color(0xFFF48FB1),
    categories: "Makeup",
  ),
  Product(
    id: 27,
    title: "Brush",
    price: 35,
    size: 12,
    description: dummyText,
    image: "assets/images/makeup_3.png",
    color: Color(0xFFF48FB1),
    categories: "Makeup",
  ),
  Product(
    id: 28,
    title: "Brush Collection",
    price: 95,
    size: 12,
    description: dummyText,
    image: "assets/images/makeup_4.png",
    color: Color(0xFFF48FB1),
    categories: "Makeup",
  ),
];

String dummyText =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since. When an unknown printer took a galley.";
